#!/usr/bin/env python3
"""Generate Pony HMAC-SHA256 Wycheproof vectors.

The generated file is intentionally checked in so normal Pony tests run
offline. Re-run this script when updating the pinned Wycheproof commit.
"""

import json
import urllib.request


WYCHEPROOF_COMMIT = "878e5366008753df2064d40c49f8e2f50f9c6af7"
VECTOR_URL = (
    "https://raw.githubusercontent.com/C2SP/wycheproof/"
    f"{WYCHEPROOF_COMMIT}/testvectors_v1/hmac_sha256_test.json"
)
OUTPUT = "ponycrypt_test/wycheproof_hmac_sha256_vectors.pony"


def pony_string(value: str) -> str:
    return json.dumps(value, separators=(",", ":"))


def main() -> None:
    with urllib.request.urlopen(VECTOR_URL) as response:
        data = json.load(response)

    cases = []
    for group in data["testGroups"]:
        tag_size = int(group["tagSize"])
        for test in group["tests"]:
            cases.append(
                {
                    "id": int(test["tcId"]),
                    "comment": test["comment"],
                    "key": test["key"],
                    "msg": test["msg"],
                    "mac": test["tag"],
                    "tag_size": tag_size,
                    "valid": test["result"] == "valid",
                }
            )

    with open(OUTPUT, "w", encoding="utf-8") as out:
        out.write(
            "// Generated by tools/update_wycheproof_hmac_sha256.py.\n"
            f"// Source: C2SP/wycheproof {WYCHEPROOF_COMMIT}\n"
            "// File: testvectors_v1/hmac_sha256_test.json\n\n"
            "class val WycheproofHmacSha256Case\n"
            "  let id: USize\n"
            "  let tag_size: USize\n"
            "  let key: String\n"
            "  let msg: String\n"
            "  let mac: String\n"
            "  let valid: Bool\n"
            "  let comment: String\n\n"
            "  new val create(\n"
            "    id': USize,\n"
            "    tag_size': USize,\n"
            "    key': String,\n"
            "    msg': String,\n"
            "    mac': String,\n"
            "    valid': Bool,\n"
            "    comment': String)\n"
            "  =>\n"
            "    id = id'\n"
            "    tag_size = tag_size'\n"
            "    key = key'\n"
            "    msg = msg'\n"
            "    mac = mac'\n"
            "    valid = valid'\n"
            "    comment = comment'\n\n"
            "primitive WycheproofHmacSha256Vectors\n"
            "  fun apply(): Array[WycheproofHmacSha256Case val] val =>\n"
            "    recover val\n"
            "      [\n"
        )

        for case in cases:
            out.write(
                "        WycheproofHmacSha256Case("
                f"{case['id']}, "
                f"{case['tag_size']}, "
                f"{pony_string(case['key'])}, "
                f"{pony_string(case['msg'])}, "
                f"{pony_string(case['mac'])}, "
                f"{str(case['valid']).lower()}, "
                f"{pony_string(case['comment'])})\n"
            )

        out.write(
            "      ]\n"
            "    end\n"
        )


if __name__ == "__main__":
    main()
