#!/usr/bin/env python3
"""Generate deterministic secp256k1 property-test inputs."""

import hashlib
import json


P = int("fffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f", 16)
N = int("fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141", 16)
OUTPUT = "ponycrypt_test/secp256k1_property_vectors.pony"


def pony_string(value: str) -> str:
    return json.dumps(value, separators=(",", ":"))


def sample(label: str, i: int, modulus: int) -> str:
    seed = hashlib.sha512(f"ponycrypt {label} {i}".encode()).digest()
    return f"{(int.from_bytes(seed, 'big') % (modulus - 1)) + 1:064x}"


def main() -> None:
    field_triples = [
        (sample("field-a", i, P), sample("field-b", i, P), sample("field-c", i, P))
        for i in range(1, 33)
    ]
    scalar_triples = [
        (sample("scalar-a", i, N), sample("scalar-b", i, N), sample("scalar-c", i, N))
        for i in range(1, 33)
    ]
    point_pairs = []
    for i in range(1, 17):
        a = int(sample("point-a", i, N), 16)
        b = int(sample("point-b", i, N), 16)
        sum_ab = (a + b) % N
        double_a = (a * 2) % N
        if sum_ab == 0:
            sum_ab = 1
        if double_a == 0:
            double_a = 1
        point_pairs.append((f"{a:064x}", f"{b:064x}", f"{sum_ab:064x}", f"{double_a:064x}"))

    with open(OUTPUT, "w", encoding="utf-8") as out:
        out.write(
            "// Generated by tools/update_secp256k1_property_vectors.py.\n\n"
            "class val Secp256k1TripleCase\n"
            "  let a: String\n"
            "  let b: String\n"
            "  let c: String\n\n"
            "  new val create(a': String, b': String, c': String) =>\n"
            "    a = a'\n"
            "    b = b'\n"
            "    c = c'\n\n"
            "class val Secp256k1PointPairCase\n"
            "  let a: String\n"
            "  let b: String\n"
            "  let sum: String\n"
            "  let double_a: String\n\n"
            "  new val create(a': String, b': String, sum': String, double_a': String) =>\n"
            "    a = a'\n"
            "    b = b'\n"
            "    sum = sum'\n"
            "    double_a = double_a'\n\n"
            "primitive Secp256k1FieldPropertyVectors\n"
            "  fun apply(): Array[Secp256k1TripleCase val] val =>\n"
            "    recover val\n"
            "      [\n"
        )
        for a, b, c in field_triples:
            out.write(
                "        Secp256k1TripleCase("
                f"{pony_string(a)}, {pony_string(b)}, {pony_string(c)})\n"
            )
        out.write(
            "      ]\n"
            "    end\n\n"
            "primitive Secp256k1ScalarPropertyVectors\n"
            "  fun apply(): Array[Secp256k1TripleCase val] val =>\n"
            "    recover val\n"
            "      [\n"
        )
        for a, b, c in scalar_triples:
            out.write(
                "        Secp256k1TripleCase("
                f"{pony_string(a)}, {pony_string(b)}, {pony_string(c)})\n"
            )
        out.write(
            "      ]\n"
            "    end\n\n"
            "primitive Secp256k1PointPropertyVectors\n"
            "  fun apply(): Array[Secp256k1PointPairCase val] val =>\n"
            "    recover val\n"
            "      [\n"
        )
        for a, b, sum_ab, double_a in point_pairs:
            out.write(
                "        Secp256k1PointPairCase("
                f"{pony_string(a)}, {pony_string(b)}, "
                f"{pony_string(sum_ab)}, {pony_string(double_a)})\n"
            )
        out.write(
            "      ]\n"
            "    end\n"
        )


if __name__ == "__main__":
    main()
