#!/usr/bin/env python3
"""Generate deterministic ECDSA/secp256k1 vectors via OpenSSL.

This uses Python's cryptography package, which delegates EC operations to
OpenSSL. The generated Pony file is checked in so regular tests do not need
Python or OpenSSL at runtime.
"""

import hashlib
import json

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import ec, utils


OUTPUT = "ponycrypt_test/openssl_ecdsa_secp256k1_vectors.pony"
N = int(
    "fffffffffffffffffffffffffffffffebaaedce6af48a03bbfd25e8cd0364141",
    16,
)


def pony_string(value: str) -> str:
    return json.dumps(value, separators=(",", ":"))


def private_keys() -> list[int]:
    keys = [
        1,
        2,
        3,
        5,
        17,
        255,
        256,
        N - 2,
        N - 1,
    ]

    for i in range(1, 25):
        seed = hashlib.sha512(f"ponycrypt openssl secp256k1 private {i}".encode()).digest()
        keys.append((int.from_bytes(seed, "big") % (N - 1)) + 1)

    return keys


def message_for(i: int) -> bytes:
    seed = hashlib.sha512(f"ponycrypt openssl secp256k1 message {i}".encode()).digest()
    size = (seed[0] % 97) + (i % 5)
    out = bytearray()
    counter = 0
    while len(out) < size:
        out.extend(hashlib.sha256(seed + counter.to_bytes(4, "big")).digest())
        counter += 1
    return bytes(out[:size])


def main() -> None:
    cases = []
    for i, d in enumerate(private_keys(), start=1):
        private_key = ec.derive_private_key(d, ec.SECP256K1())
        public_numbers = private_key.public_key().public_numbers()
        msg = message_for(i)
        digest = hashlib.sha256(msg).digest()
        der = private_key.sign(
            digest,
            ec.ECDSA(utils.Prehashed(hashes.SHA256()), deterministic_signing=True),
        )
        r, s = utils.decode_dss_signature(der)

        private_key.public_key().verify(
            der,
            digest,
            ec.ECDSA(utils.Prehashed(hashes.SHA256())),
        )

        cases.append(
            {
                "id": i,
                "private_key": f"{d:064x}",
                "public_key": "04" + f"{public_numbers.x:064x}" + f"{public_numbers.y:064x}",
                "msg": msg.hex(),
                "digest": digest.hex(),
                "signature": f"{r:064x}{s:064x}",
                "comment": "OpenSSL deterministic ECDSA",
            }
        )

    with open(OUTPUT, "w", encoding="utf-8") as out:
        out.write(
            "// Generated by tools/update_openssl_ecdsa_secp256k1_vectors.py.\n"
            "// Source: Python cryptography/OpenSSL deterministic ECDSA over secp256k1.\n\n"
            "class val OpenSslEcdsaSecp256k1Case\n"
            "  let id: USize\n"
            "  let private_key: String\n"
            "  let public_key: String\n"
            "  let msg: String\n"
            "  let digest: String\n"
            "  let signature: String\n"
            "  let comment: String\n\n"
            "  new val create(\n"
            "    id': USize,\n"
            "    private_key': String,\n"
            "    public_key': String,\n"
            "    msg': String,\n"
            "    digest': String,\n"
            "    signature': String,\n"
            "    comment': String)\n"
            "  =>\n"
            "    id = id'\n"
            "    private_key = private_key'\n"
            "    public_key = public_key'\n"
            "    msg = msg'\n"
            "    digest = digest'\n"
            "    signature = signature'\n"
            "    comment = comment'\n\n"
            "primitive OpenSslEcdsaSecp256k1Vectors\n"
            "  fun apply(): Array[OpenSslEcdsaSecp256k1Case val] val =>\n"
            "    recover val\n"
            "      [\n"
        )

        for case in cases:
            out.write(
                "        OpenSslEcdsaSecp256k1Case("
                f"{case['id']}, "
                f"{pony_string(case['private_key'])}, "
                f"{pony_string(case['public_key'])}, "
                f"{pony_string(case['msg'])}, "
                f"{pony_string(case['digest'])}, "
                f"{pony_string(case['signature'])}, "
                f"{pony_string(case['comment'])})\n"
            )

        out.write(
            "      ]\n"
            "    end\n"
        )


if __name__ == "__main__":
    main()
