#!/usr/bin/env python3
"""Generate Pony ECDSA/secp256k1/SHA-256 Wycheproof P1363 vectors.

The generated file is intentionally checked in so normal Pony tests run
offline. Re-run this script when updating the pinned Wycheproof commit.
"""

import json
import urllib.request


WYCHEPROOF_COMMIT = "878e5366008753df2064d40c49f8e2f50f9c6af7"
VECTOR_URL = (
    "https://raw.githubusercontent.com/C2SP/wycheproof/"
    f"{WYCHEPROOF_COMMIT}/testvectors_v1/"
    "ecdsa_secp256k1_sha256_p1363_test.json"
)
OUTPUT = "ponycrypt_test/wycheproof_ecdsa_secp256k1_p1363_vectors.pony"


def pony_string(value: str) -> str:
    return json.dumps(value, separators=(",", ":"))


def main() -> None:
    with urllib.request.urlopen(VECTOR_URL) as response:
        data = json.load(response)

    cases = []
    for group in data["testGroups"]:
        if group["sha"] != "SHA-256":
            continue

        public_key = group["publicKey"]["uncompressed"]
        for test in group["tests"]:
            cases.append(
                {
                    "id": int(test["tcId"]),
                    "comment": test["comment"],
                    "public_key": public_key,
                    "msg": test["msg"],
                    "sig": test["sig"],
                    "valid": test["result"] == "valid",
                }
            )

    with open(OUTPUT, "w", encoding="utf-8") as out:
        out.write(
            "// Generated by tools/update_wycheproof_ecdsa_secp256k1_p1363.py.\n"
            f"// Source: C2SP/wycheproof {WYCHEPROOF_COMMIT}\n"
            "// File: testvectors_v1/ecdsa_secp256k1_sha256_p1363_test.json\n\n"
            "class val WycheproofEcdsaSecp256k1P1363Case\n"
            "  let id: USize\n"
            "  let public_key: String\n"
            "  let msg: String\n"
            "  let sig: String\n"
            "  let valid: Bool\n"
            "  let comment: String\n\n"
            "  new val create(\n"
            "    id': USize,\n"
            "    public_key': String,\n"
            "    msg': String,\n"
            "    sig': String,\n"
            "    valid': Bool,\n"
            "    comment': String)\n"
            "  =>\n"
            "    id = id'\n"
            "    public_key = public_key'\n"
            "    msg = msg'\n"
            "    sig = sig'\n"
            "    valid = valid'\n"
            "    comment = comment'\n\n"
            "primitive WycheproofEcdsaSecp256k1P1363Vectors\n"
            "  fun apply(): Array[WycheproofEcdsaSecp256k1P1363Case val] val =>\n"
            "    recover val\n"
            "      [\n"
        )

        for case in cases:
            out.write(
                "        WycheproofEcdsaSecp256k1P1363Case("
                f"{case['id']}, "
                f"{pony_string(case['public_key'])}, "
                f"{pony_string(case['msg'])}, "
                f"{pony_string(case['sig'])}, "
                f"{str(case['valid']).lower()}, "
                f"{pony_string(case['comment'])})\n"
            )

        out.write(
            "      ]\n"
            "    end\n"
        )


if __name__ == "__main__":
    main()
