#!/usr/bin/env python3
"""Generate Pony AES-CBC-PKCS5 Wycheproof vectors.

The generated file is intentionally checked in so normal Pony tests run
offline. Re-run this script when updating the pinned Wycheproof commit.
"""

import json
import urllib.request


WYCHEPROOF_COMMIT = "878e5366008753df2064d40c49f8e2f50f9c6af7"
VECTOR_URL = (
    "https://raw.githubusercontent.com/C2SP/wycheproof/"
    f"{WYCHEPROOF_COMMIT}/testvectors_v1/aes_cbc_pkcs5_test.json"
)
OUTPUT = "ponycrypt_test/wycheproof_aes_cbc_pkcs5_vectors.pony"


def pony_string(value: str) -> str:
    return json.dumps(value, separators=(",", ":"))


def main() -> None:
    with urllib.request.urlopen(VECTOR_URL) as response:
        data = json.load(response)

    cases = []
    for group in data["testGroups"]:
        key_size = int(group["keySize"])
        for test in group["tests"]:
            cases.append(
                {
                    "id": int(test["tcId"]),
                    "comment": test["comment"],
                    "key_size": key_size,
                    "key": test["key"],
                    "iv": test["iv"],
                    "msg": test["msg"],
                    "ct": test["ct"],
                    "valid": test["result"] == "valid",
                }
            )

    with open(OUTPUT, "w", encoding="utf-8") as out:
        out.write(
            "// Generated by tools/update_wycheproof_aes_cbc_pkcs5.py.\n"
            f"// Source: C2SP/wycheproof {WYCHEPROOF_COMMIT}\n"
            "// File: testvectors_v1/aes_cbc_pkcs5_test.json\n\n"
            "class val WycheproofAesCbcPkcs5Case\n"
            "  let id: USize\n"
            "  let key_size: USize\n"
            "  let key: String\n"
            "  let iv: String\n"
            "  let msg: String\n"
            "  let ct: String\n"
            "  let valid: Bool\n"
            "  let comment: String\n\n"
            "  new val create(\n"
            "    id': USize,\n"
            "    key_size': USize,\n"
            "    key': String,\n"
            "    iv': String,\n"
            "    msg': String,\n"
            "    ct': String,\n"
            "    valid': Bool,\n"
            "    comment': String)\n"
            "  =>\n"
            "    id = id'\n"
            "    key_size = key_size'\n"
            "    key = key'\n"
            "    iv = iv'\n"
            "    msg = msg'\n"
            "    ct = ct'\n"
            "    valid = valid'\n"
            "    comment = comment'\n\n"
            "primitive WycheproofAesCbcPkcs5Vectors\n"
            "  fun apply(): Array[WycheproofAesCbcPkcs5Case val] val =>\n"
            "    recover val\n"
            "      [\n"
        )

        for case in cases:
            out.write(
                "        WycheproofAesCbcPkcs5Case("
                f"{case['id']}, "
                f"{case['key_size']}, "
                f"{pony_string(case['key'])}, "
                f"{pony_string(case['iv'])}, "
                f"{pony_string(case['msg'])}, "
                f"{pony_string(case['ct'])}, "
                f"{str(case['valid']).lower()}, "
                f"{pony_string(case['comment'])})\n"
            )

        out.write(
            "      ]\n"
            "    end\n"
        )


if __name__ == "__main__":
    main()
